### ISSUE TITLE
Minimum value reached too quickly

### ISSUE THREAD

**Issue by grant-h** [CTFd/DynamicValueChallenge#1]
The solve score calculation should be converting integers to floats.
https://github.com/CTFd/DynamicValueChallenge/blob/dd04b60eecd61a53602bf2d2345fedfaa23ee4a5/__init__.py#L176

Otherwise this undergoes integer division in Python 2.7 and doesn't work. (goes extremely negative).
This causes the challenge to reach its minimum value sooner than it should based off its decay value. 

We had to make a hotfix for this during SwampCTF 😟

**Comment by ColdHeat** [comment]
Hey dude sorry to hear that. I'm going to look into this right now.

**Comment by ColdHeat** [comment]
Closed in b9e416fc108e900d275149de3e1c5ad9456d4e03
