### ISSUE TITLE
Auto-update Challenge Points on Dynamic Parameter Update

### ISSUE THREAD

**Issue by grant-h** [CTFd/DynamicValueChallenge#3]
When changing a challenge's dynamic scoring, the value of the challenge is not updated until a new solve is submitted. I propose an option to automatically recalculate scoring changes upon parameter changes.

**Comment by ColdHeat** [comment]
Yeah this should happen on updates. Should be pretty easy to do.

**Comment by ColdHeat** [comment]
This was implemented in the main CTFd repo where dynamic challenges has been integrated in.
