### ISSUE TITLE
Confirmation request

### ISSUE THREAD

**Issue by mmr16648** [CTFd/DynamicValueChallenge#9]
When a new answer is made, the points of those who have already responded are also reduced.
Is this a bug?

**Comment by ColdHeat** [comment]
Depends on what you mean. It is intentional that those who have already solved the challenge will have their points reduced. That is the intention of this plugin. 

If you mean to say that anyone who has submitted anything (wrong or right) is losing points, that is a bug.

**Comment by mmr16648** [comment]
Yes.
I mean to say that anyone who has submitted anything (wrong or right) is losing points.
I'm sorry, my English is not good

**Comment by whirlwind110** [comment]
有两种理解
1、如果做出来人越多，说明题目简单，分数所有人都降低，从一定程度上防止换flag。
2、越先做出来的人，得分越高，往后递减，这个我们公司写了这样的插件，他这个不行。

There are two understandings.

1. The more people get flag, means that challenge is easy. reduced everyone's score.Preventing cheating to a certain extent
2. The people who get flag faster, the higher the score, and after solves reduced, I will share this plugin.
